// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atlnxtoapjbvyvykshlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bG54dG9hcGpidnl2eWtzaGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODIyMTAsImV4cCI6MjA2Mjc1ODIxMH0.pO5HOl_yEga0ufV3oXGgXVnvdVKN9_yuXJNlNtXWZ88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);